### ISSUE TITLE
Event should track orientationchange

### ISSUE THREAD

**Issue by danghs** [afram/volley#1]
Resize isn't always triggered on orientation change

```
function listen() {
  window.addEventListener('resize', debounce(handleResize, 500));
}
```

Should be

```
function listen() {
  window.addEventListener('resize orientationchange', debounce(handleResize, 500));
}
```

**Comment by afram** [comment]
Hey bud,

most devices that fire the orientationchange event also fire the resize event.

http://www.quirksmode.org/dom/events/resize_mobile.html
http://www.quirksmode.org/dom/events/orientationchange.html

Despite this, in order to limit the noise - I think `orientationchange` is more meaningful than calling the handler on say activating the keyboard for example - I will fire the `orientationchange` event in place of the `resize` event on devices that support it.

**Comment by afram** [comment]
Actually, thinking about devices like the Microsoft Surface, it is probably better to fire a resize event as someone resizing the browser on a tablet != orientationchange.

I'm going to leave it as is :-)

**Comment by afram** [comment]
@danghs 

After our conversation, I have added orientationchange to support older i-devices
https://github.com/afram/volley/blob/master/lib/breakpoints.js#L32
